#!/bin/bash
#
# Made by Ivann LARUELLE / larueli on GitHub and Docker Hub
# decidim-nonroot on Docker Hub and GitHub
#
echo "Container made by Ivann LARUELLE <ivann.laruelle@gmail.com>"
echo "You will find more info on DockerHub and GitHub : larueli/decidim-nonroot"
echo "-------------------------------------------------------------------------"
echo "---- Initialization of the container ----"
export RAILS_ENV=production
cd /decidim-app
echo "---- Execute init scripts ----"
if [ -d /docker-entrypoint-initdecidim.d ]
then
	if [ ! -z $(ls /docker-entrypoint-initdecidim.d/) ]
	then
		for f in /docker-entrypoint-initdecidim.d/*; do
  		echo "     - Running $f"
  		bash "$f" -H 
		done
	fi
fi
RAILS_ENV=production bin/rails decidim:upgrade
sed -i 's/# config.force_ssl = true/config.force_ssl = false/' config/environments/production.rb
sed -i 's/# config.force_ssl = true/config.force_ssl = false/' config/initializers/decidim.rb
echo "---- Connecting to DB ----"
echo "If db already exists, show errors, no worries !"
RAILS_ENV=production bin/rails db:migrate
echo "---- Launch Server ----"
RAILS_ENV=production bin/delayed_job start
RAILS_ENV=production bin/rails s
